### ISSUE TITLE
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

### ISSUE THREAD

**Issue by xtuyaowu** [jrobchin/phormatics#1]
got such errors,help!
[phormatics]# python server/app.py 
Traceback (most recent call last):
  File "server/app.py", line 27, in <module>
    pose_estimator = TfPoseEstimator(graph_path=settings.GRAPH_PATH, target_size=settings.PROCESSING_DIMS)
  File "/data/app/yaowu/phormatics/server/helpers/estimator.py", line 257, in __init__
    graph_def.ParseFromString(f.read())
  File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /data/app/yaowu/phormatics/models/mobilenet/graph_opt.pb; No such file or directory
Exception ignored in: <bound method TfPoseEstimator.__del__ of <helpers.estimator.TfPoseEstimator object at 0x7fdeb5b2da58>>
Traceback (most recent call last):
  File "/data/app/yaowu/phormatics/server/helpers/estimator.py", line 280, in __del__
    self.persistent_sess.close()
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

**Comment by snehmehta** [comment]
> got such errors,help!
> [phormatics]# python server/app.py
> Traceback (most recent call last):
> File "server/app.py", line 27, in 
> pose_estimator = TfPoseEstimator(graph_path=settings.GRAPH_PATH, target_size=settings.PROCESSING_DIMS)
> File "/data/app/yaowu/phormatics/server/helpers/estimator.py", line 257, in **init**
> graph_def.ParseFromString(f.read())
> File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
> self._preread_check()
> File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/data/app/Anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /data/app/yaowu/phormatics/models/mobilenet/graph_opt.pb; No such file or directory
> Exception ignored in: <bound method TfPoseEstimator.**del** of <helpers.estimator.TfPoseEstimator object at 0x7fdeb5b2da58>>
> Traceback (most recent call last):
> File "/data/app/yaowu/phormatics/server/helpers/estimator.py", line 280, in **del**
> self.persistent_sess.close()
> AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

hey i got same error so did you find any solution for it
